---
- name: Install
  apt: pkg=memcached state=present
  become: yes
  become_method: sudo

- name: Enable on boot
  service: name=memcached state=started enabled=yes
  become: yes
  become_method: sudo
